server:
  port: 8081
# Dubbo的配置
dubbo:
  application:
    name: account-book-web
  registry:
    address: zookeeper://192.168.3.203:2181
  monitor:
    protocol: registry

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  redis:
    host: 192.168.3.203
    port: 6379
    database: 0